### ISSUE TITLE
Request for Dart Version Reversion

### ISSUE THREAD

**Issue by noifuji** [jemisgoti/simple_ripple_animation#4]
Hello, jemisgoti.

From version 0.0.8, this library now requires Dart SDK version "3.1.3 or higher". 
Considering [Flutter and Dart compatibility,](https://docs.flutter.dev/release/archive?tab=windows) this means that your library requires Flutter version "3.13.6 or higher". 
However, Flutter's version requirement is still "1.17.0 or higher".
If this change is unintened, could you revert the Dart version back to "2.9.0 or higher"?

```
name: simple_ripple_animation
description: This package provide ripple animation widget that is easy to set up and customise, and it looks beautiful in any color you choose.
version: 0.0.8
homepage: https://github.com/jemisgoti/simple_ripple_animation

environment:
  sdk: '>=3.1.3 <4.0.0'               //here
  flutter: ">=1.17.0"
```

**Comment by jemisgoti** [comment]
@noifuji Thanks for your attention. I will revert dart version back to 2.17.0.

**Comment by noifuji** [comment]
Thank you!

**Comment by noifuji** [comment]
I tried the latest library in a Dart 2.19 environment, but it didn't work well.
It seems that the library has a dependency on hyper_lint, which requires Dart 3.1.3 or higher. 
Since hyper_lint seems to be yours, could you also consider updating it?

**Comment by jemisgoti** [comment]
Try version 0.0.7. In future it will intend to support latest version only.

**Comment by noifuji** [comment]
I found out that simple_ripple_animation was not directly importing hyper_lint.
If you use hyper_lint only during development,  it should be under dev_dependencies.

Then you don't need to change Dart version of hyper_lint.😉

like this
```
version: 0.0.9
homepage: https://github.com/jemisgoti/simple_ripple_animation
repository: https://github.com/jemisgoti/simple_ripple_animation
issue_tracker: https://github.com/jemisgoti/simple_ripple_animation/issues
documentation: https://jemisgoti.github.io/simple_ripple_animation

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"
  

dependencies:
  flutter:
    sdk: flutter
  hyper_lint: ^0.0.1   //remove

dev_dependencies:
  flutter_test:
    sdk: flutter
  hyper_lint: ^0.0.1  //add
```
